const testConstants = {
    POST_TITLE: 'Dummy Post Title',
    CREATE_POST: 'Create Post Dummy',
    INITIAL_CAPTION: 'Provide some engaging content here. Max 2200 characters allowed.',
    CAPTION_OK_BTNTEXT: 'OK',
    USER_DESCRIPTION: '#AutomationTestUser',
    MEDIA_LIMIT_ALERT: 'You cannot select more than 10 images/videos',
    CAPTION_ALERT: 'Please enter a caption',
    AUTHOR_NAME: 'Dummy Author Name',
    DURATION: 'Now',
    CROP_TITLE: 'Edit Image',
    LINK_TITLE: 'Link Title',
    SHARE_LINK: 'Share Your Link',
    EMAIL_PLACEHOLDER: 'Enter your email address',
    PASSWORD_PLACEHOLDER: 'Enter your password',
    EMAIL_EMPTY_ERROR: 'Email address is required',
    PASSWORD_EMPTY_ERROR: 'Password is required',
    INVALID_EMAIL_ERROR: 'Please enter a valid email address',
    FOLLOW_TEXT: 'Follow User',
    SHARE_LINK_TITLE: 'Share a Story Link',
    SHARE_LINK_DESCRIPTION: 'Share a link to a story or anything you find interesting.',
    INVALID_LINK: 'InvalidLink12345',
    VALID_LINK: 'https://www.dummywebsite.com/',
    LINK_WITHOUT_DETAILS: 'https://www.dummy.com/',
    EXTRACT_TITLE: 'Extracted Title',
    INVALID_LINK_ERROR: 'Unsupported link type',
    LINK_PLACEHOLDER_TEXT: 'Paste or enter a valid link',
    LINK_IMAGE_PLACEHOLDER: 'Add image preview',
    LINK_TITLE_PLACEHOLDER: 'Add title for your link',
    LINK_ALERT: 'Please enter a link title',
    USER_TITLE: 'My User Title',
    EMPTY_PROFILE_HEADING: 'Create Your Profile',
    EMPTY_PROFILE_DESCRIPTION: 'Create your profile to explore personalized content and opportunities.',
    FIRST_SIDE_HEADING: '1. Add your work',
    FIRST_SIDE_DESCRIPTION: 'Add projects or work experience details',
    SECOND_SIDE_HEADING: '2. Share your passion',
    SECOND_SIDE_DESCRIPTION: 'Share side projects, speaking gigs, or passions',
    THIRD_SIDE_HEADING: '3. Show your work',
    THIRD_SIDE_DESCRIPTION: 'Post images, videos, and case studies to showcase your work',
    OTHER_PROFILE_ABOUT: 'No information added yet',
    OTHER_PROFILE_UPVOTES: 'No upvotes yet',
    OTHER_PROFILE_REPLIES: 'No comments yet',
    SIGN_UP: 'Sign Up Now',
    SIGN_UP_DESCRIPTION: 'Sign up to personalize your feed and discover new content.',
    BIRTHDAY: 'Select Birthday',
    FIRSTNAME_TEXT: 'Enter First Name',
    LASTNAME_TEXT: 'Enter Last Name',
    EMAIL_ADDRESS: 'Email Address',
    OTP_TITLE: 'Enter Verification Code',
    OTP_DESCRIPTION: 'Check your email for a verification code.',
    PASSWORD_DESCRIPTION: 'Choose a secure password',
    PASSWORD_FIELD_PLACEHOLDER: 'Your password',
    CHARLENGTH_VALIDATION: 'Password must be 8 characters or more',
    CHARCASE_VALIDATION: 'Use both upper and lower case letters',
    NUM_SPECIALCHAR_VALIDATION: 'Password must contain numbers and special characters',
    FIRST_NAME: 'TestFirstName',
    SECOND_NAME: 'TestLastName',
    CLEAR_FIELD: '',
    COMMENT_FIELD_PLACEHOLDER: 'Type your comment...',
    COMMENT_POST_BUTTON: 'Post Comment',
    MESSAGE_RECEIVER: 'Dummy Receiver',
    MESSAGE_SENDER: 'Dummy Sender',
    MESSAGE_BOX_TEXT: 'Enter your message...',
    POST_TAB_HEADING: 'Create Posts on Platform',
    POST_TAB_DESCRIPTION: 'Post your work, interests, or case studies with images, videos, or links.',
    UPVOTE_TAB_HEADING: 'You haven\'t upvoted any posts yet',
    UPVOTE_TAB_DESCRIPTION: 'Upvote posts you like to see them here.',
    REPLIES_TAB_HEADING: 'You haven\'t commented on any posts yet',
    REPLIES_TAB_DESCRIPTION: 'Comment on posts to engage in discussions.',
    CHATS_PER_PAGE: 8,
    MAX_COMMENTS: 3,
    SEARCH_TEXT: 'Search Term',
    SEARCH_NO_RESULT: 'No results found for: ',
    EXACT_MATCH_TERM: 'ExactMatch_Example',
    PARTIAL_SEARCH: 'Search',
    NOTIFICATION_TITLE: 'Your Notifications',
    NOTIFICATIONS_HEADER: 'Notifications List',
    NOTIFICATIONS_UPVOTE: 'User Upvoted your post',
    NOTIFICATIONS_COMMENT: 'User commented on your post'
};

module.exports = testConstants;
